# Generated by Django 2.1.3 on 2018-11-19 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('idAct', models.AutoField(primary_key=True, serialize=False)),
                ('nomAct', models.CharField(choices=[('c', 'Conges'), ('m', 'Maladie'), ('a', 'Absence'), ('d', 'Deplacement'), ('rao', 'RAO'), ('alt', 'Alternance'), ('au', 'Autres')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('nomCl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('trigrammeC', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nomC', models.CharField(max_length=50)),
                ('prenomC', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('RdP', 'Responsable de projet'), ('IE', 'Ingénieur étude'), ('Stg', 'Stagiaire')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('charges', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('chargesRAF', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_commande', models.DateField()),
                ('etablie', models.BooleanField(default=False)),
                ('commentaire', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('idEquipe', models.AutoField(primary_key=True, serialize=False)),
                ('nomE', models.CharField(choices=[('PyWe', 'PythonWeb'), ('PyQt', 'PythonQt'), ('CPQt', 'CPlusQt')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('idProjet', models.AutoField(primary_key=True, serialize=False)),
                ('nomP', models.CharField(max_length=50)),
                ('RT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respT', to='pdc_core_app.Collaborateur')),
                ('RdP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respP', to='pdc_core_app.Collaborateur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='RepartitionActivite',
            fields=[
                ('idRA', models.AutoField(primary_key=True, serialize=False)),
                ('list_RA', models.CharField(max_length=1000)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Activite')),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='RepartitionProjet',
            fields=[
                ('idRP', models.AutoField(primary_key=True, serialize=False)),
                ('list_R', models.CharField(max_length=1000)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Collaborateur')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_E',
            fields=[
                ('idRespE', models.AutoField(primary_key=True, serialize=False)),
                ('RdE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Collaborateur')),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Equipe')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Equipe'),
        ),
        migrations.AddField(
            model_name='commande',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Projet'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Equipe'),
        ),
    ]
