# Generated by Django 2.1.3 on 2018-11-20 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import month.models


def pourcentage(apps, schema_editor):
    Pourcentage = apps.get_model("pdc_core_app", "Pourcentage")
    db_alias = schema_editor.connection.alias
    for n in range(0, 105, 5):
        Pourcentage.objects.using(db_alias).create(pourcentage=n)


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pourcentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='RDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField(help_text='some help...', verbose_name='Month Value')),
                ('pourcentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Pourcentage')),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='chargesRAF',
            field=models.FloatField(default=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]), validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.RemoveField(
            model_name='repartitionactivite',
            name='list_RA',
        ),
        migrations.RemoveField(
            model_name='repartitionprojet',
            name='list_R',
        ),
        migrations.AddField(
            model_name='repartitionactivite',
            name='list_RA',
            field=models.ManyToManyField(to='pdc_core_app.RDate'),
        ),
        migrations.AddField(
            model_name='repartitionprojet',
            name='list_R',
            field=models.ManyToManyField(to='pdc_core_app.RDate'),
        ),
        migrations.RunPython(pourcentage)
    ]
