# Generated by Django 2.1.3 on 2018-11-20 13:47

import django.core.validators
from django.db import migrations, models


def pourcentage(apps, schema_editor):
    Pourcentage = apps.get_model("pdc_core_app", "Pourcentage")
    db_alias = schema_editor.connection.alias
    for n in range(0, 105, 5):
        Pourcentage.objects.using(db_alias).create(
            pourcentage=n
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0002_auto_20181120_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='chargesRAF',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.RunPython(pourcentage)
    ]
