# Generated by Django 2.1.4 on 2018-12-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdc_core_app', '0003_auto_20181120_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='odds',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Equipe'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Equipe'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='RT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respT', to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='RdP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respP', to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Client'),
        ),
        migrations.AlterField(
            model_name='rdate',
            name='month',
            field=month.models.MonthField(verbose_name='Month Value'),
        ),
        migrations.AlterField(
            model_name='repartitionactivite',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='repartitionprojet',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='responsable_e',
            name='RdE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='responsable_e',
            name='equipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Equipe'),
        ),
    ]
