# Generated by Django 2.1.3 on 2018-11-20 14:30

from django.db import migrations, models
import pdc_core_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0003_auto_20181120_1347'),
    ]

    operations = [
        
    ]
