# Generated by Django 2.1.3 on 2018-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0003_auto_20181120_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartitionactivite',
            old_name='list_RA',
            new_name='list_R',
        ),
    ]
