# Generated by Django 2.1.3 on 2018-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0004_auto_20181120_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartitionactivite',
            name='list_RA',
            field=models.ManyToManyField(db_table='Affectation', to='pdc_core_app.RDate'),
        ),
    ]
