# Generated by Django 2.1.3 on 2018-11-27 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0004_auto_20181123_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='chargesRAF',
            field=models.FloatField(default=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]), validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
