# Generated by Django 2.1.3 on 2018-11-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0006_auto_20181127_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etablie',
            field=models.BooleanField(default=True),
        ),
    ]
