# Generated by Django 2.1.3 on 2018-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0008_auto_20181128_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
