# Generated by Django 2.1.4 on 2018-12-06 14:55

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0009_auto_20181130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdate',
            name='month',
            field=month.models.MonthField(verbose_name='Month Value'),
        ),
    ]
