# Generated by Django 2.1.3 on 2018-11-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0009_auto_20181120_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='collaborateurs',
            field=models.ManyToManyField(through='pdc_core_app.RepartitionProjet', to='pdc_core_app.Collaborateur'),
        ),
    ]
