# Generated by Django 2.1.4 on 2018-12-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0010_auto_20181206_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='odds',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
