# Generated by Django 2.1.3 on 2018-11-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0010_commande_collaborateurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.RDate')),
            ],
        ),
        migrations.RemoveField(
            model_name='repartitionprojet',
            name='list_R',
        ),
        migrations.AddField(
            model_name='repartitionprojet',
            name='list_R',
            field=models.ManyToManyField(through='pdc_core_app.AffectationP', to='pdc_core_app.RDate'),
        ),
        migrations.AddField(
            model_name='affectationp',
            name='repartitionprojet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.RepartitionProjet'),
        ),
    ]
