# Generated by Django 2.1.3 on 2018-11-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0011_auto_20181120_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.RDate')),
            ],
        ),
        migrations.RemoveField(
            model_name='repartitionactivite',
            name='list_RA',
        ),
        migrations.AddField(
            model_name='repartitionactivite',
            name='list_RA',
            field=models.ManyToManyField(through='pdc_core_app.AffectationA', to='pdc_core_app.RDate'),
        ),
        migrations.AddField(
            model_name='affectationa',
            name='repartitionactivite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.RepartitionActivite'),
        ),
    ]
