# Generated by Django 2.1.3 on 2018-11-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0013_auto_20181120_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationProjets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.RDate')),
            ],
        ),
        migrations.AlterField(
            model_name='repartitionprojet',
            name='list_R',
            field=models.ManyToManyField(db_table='AffectationProjets', to='pdc_core_app.RDate'),
        ),
        migrations.AddField(
            model_name='affectationprojets',
            name='repartitionprojet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.RepartitionProjet'),
        ),
    ]
