# Generated by Django 2.1.4 on 2018-12-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0013_auto_20181218_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='RT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respT', to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='RdP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respP', to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdc_core_app.Client'),
        ),
    ]
