# Generated by Django 2.1.4 on 2018-12-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0014_auto_20181218_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Equipe'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Projet'),
        ),
        migrations.AlterField(
            model_name='history',
            name='model',
            field=models.ForeignKey(help_text='Content type of the model under version control.', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='RT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respT', to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='RdP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respP', to='pdc_core_app.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Client'),
        ),
    ]
