# Generated by Django 2.1.4 on 2018-12-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdc_core_app', '0015_auto_20181218_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartitionactivite',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Activite'),
        ),
        migrations.AlterField(
            model_name='repartitionprojet',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Commande'),
        ),
        migrations.AlterField(
            model_name='responsable_e',
            name='RdE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pdc_core_app.Collaborateur'),
        ),
    ]
